local agent = require('thorny.agent')

describe('agent.new()', function()
  it('creates agent with required fields', function()
    local a = agent.new('refactor', 'You are a refactoring assistant.', 'personal', 'project')
    assert.equals('refactor', a.name)
    assert.equals('You are a refactoring assistant.', a.persona)
    assert.equals('personal', a.profile)
    assert.equals('project', a.context_mode)
    assert.same({}, a.history)
    assert.same({}, a.pending_edits)
    assert.is_nil(a.buf)
  end)

  it('defaults context_mode to project when nil', function()
    local a = agent.new('test', 'persona', 'personal', nil)
    assert.equals('project', a.context_mode)
  end)

  it('defaults provider to claude when nil', function()
    local a = agent.new('test', 'persona', 'personal', 'project', nil)
    assert.equals('claude', a.provider)
  end)

  it('accepts explicit provider name', function()
    local a = agent.new('test', 'persona', 'personal', 'project', 'kong')
    assert.equals('kong', a.provider)
  end)
end)

describe('agent.add_message()', function()
  it('appends a message to history', function()
    local a = agent.new('test', '', 'default', 'none')
    agent.add_message(a, 'user', 'hello')
    assert.equals(1, #a.history)
    assert.equals('user', a.history[1].role)
    assert.equals('hello', a.history[1].content)
  end)

  it('appends multiple messages in order', function()
    local a = agent.new('test', '', 'default', 'none')
    agent.add_message(a, 'user', 'first')
    agent.add_message(a, 'assistant', 'second')
    assert.equals(2, #a.history)
    assert.equals('user', a.history[1].role)
    assert.equals('assistant', a.history[2].role)
  end)
end)

describe('agent.add_tool_result()', function()
  it('appends a tool_result message to history', function()
    local a = agent.new('test', '', 'default', 'none')
    agent.add_tool_result(a, 'toolu_abc123', 'Edit applied successfully.')
    assert.equals(1, #a.history)
    assert.equals('user', a.history[1].role)
    assert.equals('tool_result', a.history[1].content[1].type)
    assert.equals('toolu_abc123', a.history[1].content[1].tool_use_id)
    assert.equals('Edit applied successfully.', a.history[1].content[1].content)
  end)
end)

describe('agent pending edits', function()
  it('add_pending_edit stores a tool call', function()
    local a = agent.new('test', '', 'default', 'none')
    local tc = { id = 'toolu_1', name = 'Edit', input = { file_path = 'foo.go', old_string = 'a', new_string = 'b' } }
    agent.add_pending_edit(a, tc)
    assert.equals(1, #a.pending_edits)
  end)

  it('pop_pending_edit returns and removes the most recent edit', function()
    local a = agent.new('test', '', 'default', 'none')
    agent.add_pending_edit(a, { id = 'toolu_1', name = 'Edit', input = {} })
    agent.add_pending_edit(a, { id = 'toolu_2', name = 'Write', input = {} })
    local tc = agent.pop_pending_edit(a)
    assert.equals('toolu_2', tc.id)
    assert.equals(1, #a.pending_edits)
  end)

  it('pop_pending_edit returns nil when no pending edits', function()
    local a = agent.new('test', '', 'default', 'none')
    assert.is_nil(agent.pop_pending_edit(a))
  end)
end)
