describe('thorny', function()
  it('loads without error', function()
    local ok, thorny = pcall(require, 'thorny')
    assert.is_true(ok)
    assert.is_table(thorny)
  end)

  it('setup() accepts a config table', function()
    local thorny = require('thorny')
    assert.has_no_error(function()
      thorny.setup({ default_profile = 'personal' })
    end)
    assert.equals('personal', thorny._config.default_profile)
  end)

  it('setup() accepts nil', function()
    local thorny = require('thorny')
    assert.has_no_error(function()
      thorny.setup()
    end)
  end)
end)
